services:
  web:
    build: website
    ports:
      - "3000:3000"
    environment:
      - DISCORD_WEBHOOK_URL=${discord_webhook}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3